name: women_safety_health_app
description: HerSafe — Women Safety & Health App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / Fonts
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1


  # Firebase
  path_provider: ^2.1.3
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  firebase_messaging: ^16.1.2

  # Camera
  camera: ^0.10.6

  # Location
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

  # SMS
  telephony: ^0.2.0

  # Audio recording
  record: ^5.1.2
  table_calendar: ^3.0.9


  # Sensors (shake detection)
  sensors_plus: ^4.0.2

  # Storage
  shared_preferences: ^2.2.2


  # Web helpers
  package_info_plus: ^4.0.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.4.4
  js: ^0.7.2
  telephony_fix: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true




  #assets:
  # Fonts are handled below, you can add images here if needed
  # - assets/images/


